import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Flex, Grid, Row } from "vcc-ui";
import styles from "@/styles/Home.module.css";
import cars from "@/public/api/cars.json";
import { CarItem } from "@/types/Car.model";
import CarCard from "@/components/CarCard";
import { useSelector, useDispatch } from "react-redux";
import { carAction, StoreState } from "../store/car-slice";
import Filter from "@/components/Filter";
import CustomCarousel from "@/components/CustomCarousel";

interface Props {
	carsList?: CarItem[];
}
// const Home: NextPage = (CarsList:CarItem[]) => {
const Home: NextPage = (props: Props) => {
	const { carsList = [] } = props;
	const dispatch = useDispatch();

	useEffect(() => {
		dispatch(carAction.updateCarsList({ carsList }));
	}, [dispatch, carsList]);

	const updatedCarsList: CarItem[] = useSelector(
		({ car: carSLice }: { car: StoreState }) => carSLice.updatedCarsList
	);

	return (
		<div className={styles.container}>
			<Head>
				<title>Cars Gallery App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.mains}>
				<Filter />
				<CustomCarousel>
					{updatedCarsList.map((carItem: CarItem) => {
						return <CarCard carItem={carItem} key={carItem.id} />;
					})}
				</CustomCarousel>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by {"Peter "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;

export const getServerSideProps = async () => {
	return {
		props: {
			carsList: cars,
		},
	};
};
